apiVersion: v1
kind: Service
metadata:
  name: scheduler
  labels:
    app: {{ .Release.Name }}
    component: api
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    app: {{ .Release.Name }}
    component: api
  ports:
  - port: 8000
    targetPort: 8000